-- MySQL Script generated by MySQL Workbench
-- Fri May 29 12:20:24 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ajax_note
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ajax_note
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ajax_note` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ajax_note` ;

-- -----------------------------------------------------
-- Table `ajax_note`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ajax_note`.`notes` (
  `id` INT NOT NULL,
  `note` TEXT NULL,
  `author` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
